services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8888:8888
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
  pgadmin:
    image: dpage/pgadmin4:6.10
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 15432:80
    depends_on:
      - postgres